# Generated by Django 6.0.5 on 2026-06-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETIMSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Device ID or Serial Number', max_length=100)),
                ('device_key', models.CharField(help_text='eTIMS API Key/Token', max_length=255)),
                ('branch_code', models.CharField(default='00', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='code',
            field=models.CharField(choices=[('A', '16% VAT'), ('B', '0%'), ('C', 'Exempt'), ('D', 'Non-VAT'), ('E', '8% VAT')], max_length=2, unique=True),
        ),
        migrations.CreateModel(
            name='ETIMSSaleTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_data_invoice_no', models.CharField(max_length=100)),
                ('kra_qr_code', models.TextField(blank=True, null=True)),
                ('kra_invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etims_transmission', to='pos.sale')),
            ],
        ),
    ]
