# Generated by Django 6.0.5 on 2026-06-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SALE', 'Sale'), ('REFUND', 'Refund'), ('STOCK_CHANGE', 'Stock Change'), ('PRICE_CHANGE', 'Price Change'), ('PAYMENT', 'Payment'), ('SYNC', 'Synchronization'), ('PRINT', 'Print'), ('ERROR', 'Error'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('AUTH_FAILURE', 'Authentication Failure'), ('SETTING_CHANGE', 'Setting Change')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('entity_type', models.CharField(help_text="The type of object being acted upon (e.g., 'Product', 'Sale')", max_length=100)),
                ('entity_id', models.CharField(blank=True, help_text='The ID of the object being acted upon', max_length=100, null=True)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(blank=True, help_text='The state of the entity before the change', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='The state of the entity after the change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser and OS information', null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='auditlogs_a_created_513404_idx'), models.Index(fields=['action'], name='auditlogs_a_action_b1f2ec_idx'), models.Index(fields=['entity_type'], name='auditlogs_a_entity__ce66ef_idx'), models.Index(fields=['branch_id'], name='auditlogs_a_branch__670a91_idx')],
            },
        ),
    ]
