# Generated by Django 6.0.5 on 2026-06-12 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name': 'System Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlogs_a_created_513404_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlogs_a_action_b1f2ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlogs_a_entity__ce66ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlogs_a_branch__670a91_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SALE', 'Sale'), ('REFUND', 'Refund'), ('STOCK_CHANGE', 'Stock Change'), ('PRICE_CHANGE', 'Price Change')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
