# Generated by Django 6.0.5 on 2026-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_tenants', models.IntegerField(default=0)),
                ('active_tenants', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_sales_count', models.IntegerField(default=0)),
                ('active_users_24h', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Snapshot',
                'verbose_name_plural': 'Global Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RegionalAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, unique=True)),
                ('tenant_count', models.IntegerField(default=0)),
                ('revenue_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regional Analytic',
                'verbose_name_plural': 'Regional Analytics',
            },
        ),
    ]
