# Generated by Django 6.0.5 on 2026-06-12 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('kra_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_color', models.CharField(default='#556B2F', max_length=7)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('selected_plan', models.CharField(default='growth', max_length=50)),
                ('receipt_header', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_footer', models.TextField(blank=True, null=True)),
                ('show_vat', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('can_void_sales', models.BooleanField(default=False)),
                ('can_edit_inventory', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_tenant_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can manage tenant-wide settings.'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.customrole'),
        ),
    ]
