# Generated by Django 6.0.5 on 2026-06-12 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sales_volume', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross_margin', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='inventory.branch')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
