# Generated by Django 6.0.5 on 2026-06-12 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.sale')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.saleitem')),
                ('return_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returntransaction')),
            ],
        ),
    ]
